### ISSUE TITLE
Not responsive for Mobile

### ISSUE THREAD

**Issue by suhealpasha** [justin-chu/react-fast-marquee#54] opened 2022-10-19 11:46 UTC
https://user-images.githubusercontent.com/42802652/196681770-fa7387b2-9ee5-4140-bede-cce5944cf8fc.mp4

Image is stretched in mobile version and Safari browser but works fine in Chrome Web browser.
Can you please look into this issue.

**Comment by justin-chu** [comment] 2023-04-22 06:25
Could not reproduce, closing the issue

**Closed by justin-chu** 2023-04-22 06:25 UTC
