### ISSUE TITLE
Marquee doesn't work if used twice on a page

### ISSUE THREAD

**Issue by Aycom366** [justin-chu/react-fast-marquee#52] opened 2022-10-09 17:22 UTC
marquee doesn't work if it is being used twice on a page.
```
<div className='w-full h-full'>
        <Marquee speed={300}>
          <div className='w-full  flex gap-2 relative'>
            {TwitterApi.splice(0, 10).map((item, index) => (
              <TwitterCard classes='last:mr-2' {...item} key={index} />
            ))}
          </div>
        </Marquee>
      </div>
     
```
The above is working normally but if I added extra elements to the above, it doesn't show. 
```
<div className='w-full h-full'>
        <Marquee speed={300}>
          <div className='w-full  flex gap-2 relative'>
            {TwitterApi.splice(0, 10).map((item, index) => (
              <TwitterCard classes='last:mr-2' {...item} key={index} />
            ))}
          </div>
        </Marquee>
      </div>
      <div className='w-full h-full'>
        <Marquee speed={300}>
          <div className='w-full  flex gap-2 relative'>
            {TwitterApi.splice(0, 10).map((item, index) => (
              <TwitterCard classes='last:mr-2' {...item} key={index} />
            ))}
          </div>
        </Marquee>
      </div>
```

**Comment by justin-chu** [comment] 2023-04-22 18:59
Sorry, I'm unable to reproduce this, closing for now

**Closed by justin-chu** 2023-04-22 18:59 UTC

**Comment by anistark** [comment] 2023-05-25 20:58
Happening for me too. How to fix it ? @Aycom366 @justin-chu
