### ISSUE TITLE
Overflow x

### ISSUE THREAD

**Issue by Znoy108x** [justin-chu/react-fast-marquee#56] opened 2022-12-04 18:05 UTC
![image](https://user-images.githubusercontent.com/75539409/205507650-7cf8fffa-7c80-4560-8259-e5a4ee7782b0.png)
can anyone tell me why react-fast-marqueue is overflowing in x axis ??

**Comment by justin-chu** [comment] 2023-04-22 06:25
Could not reproduce, closing the issue

**Closed by justin-chu** 2023-04-22 06:25 UTC
