### ISSUE TITLE
Large space between first and last item

### ISSUE THREAD

**Issue by PG-20** [justin-chu/react-fast-marquee#7] opened 2021-03-24 07:55 UTC
<img width="1307" alt="Screenshot 2021-03-24 at 1 22 06 PM" src="https://user-images.githubusercontent.com/45551346/112274090-0e331800-8cb9-11eb-827a-8d78395fc747.png">

There is a large space between the first and last items in the marquee and the behaviour is surprisingly very inconsistent. If i switch the viewport to mobile size, it works well, and I switch it back to desktop, it's perfect too, but when I refresh it again, back with the white space b/w first and last item. Not sure how to fix. I using the <Marquee> tag without any props currently

**Comment by justin-chu** [comment] 2021-03-24 08:39
Can you provide your code so that I can reproduce this? I will try to fix this as soon as possible.

**Comment by PG-20** [comment] 2021-03-24 08:45
Sure, but it's really nothing much
```
function OurPartners(): ReactElement {
  const classes = useStyles();

  return (
    <>
      <section className={classes.section}>
        <p className={classes.head}>
          OUR PARTNERS
        </p>
        <Marquee>
          <img
            alt="Cyberport"
            src="/images/about-logo-cyberport.png"
            className={classes.image}
          />
          <img
            className={classes.image}
            alt="Innovation and Technology Commission"
            src="/images/about-logo-innovation-and-technology-commission.png"
          />
          <img
            className={classes.image}
            alt="Invest HK"
            src="/images/about-logo-invest-hk.png"
          />
          <img
            className={classes.image}
            alt="HK Financial Services Development Council"
            src="/images/about-logo-hk-financial-services-development-council.png"
          />
          <img
            className={classes.image}
            alt="Microsoft Partner Network"
            src="/images/about-logo-microsoft-partner-network.png"
          />
          <img
            alt="AWS"
            src="/images/about-logo-aws.png"
            className={classes.image}
          />
          <img
            className={classes.image}
            alt="Tencent Cloud"
            src="/images/about-logo-tencent-cloud.png"
          />
          <img
            className={classes.image}
            alt="Alibaba"
            src="/images/about-logo-alibaba.png"
          />
        </Marquee>
      </section>
    </>
  );
}
```

**Comment by PG-20** [comment] 2021-04-21 07:56
Hi @justin-chu, any luck?
Perhaps try adding a continuous prop to the Marquee tag? Not entirely sure how that will work though. I see that the demo is working fine on your website but I'm having trouble making mine work continuously, would be great if you could help me out!

**Comment by justin-chu** [comment] 2021-04-21 19:44
Hey @PG-20, sorry, I should have a fix pushed by next week. A temporary fix for you might be to paste all the components multiple times as the children of the marquee.

**Comment by PG-20** [comment] 2021-04-22 07:30
Great, I'll wait. So I guess you found the bug then? What was the issue?

**Comment by justin-chu** [comment] 2021-04-23 06:54
It's most likely due to it only repeating the child components twice, so larger screens may have a gap between the last and first component. There might be a couple other bugs to that I'll fix soon.

**Comment by aliiip** [comment] 2021-05-10 22:26
Any update on this issue? I'm also facing a problem with a gap between the first and last component on large screens.

**Comment by justin-chu** [comment] 2021-05-11 01:14
Sorry @aliiip, I've been trying to find a way to repeat the children dynamically, but the problem is harder than I initially thought it would be.

**Comment by maximousblk** [comment] 2022-04-09 09:45
I've been experimenting with ways to fix this and i think i have found the problem.

setting the `min-width: 100%` to `min-width: max-content` or anything that has a similar effect solves this problem

https://github.com/justin-chu/react-fast-marquee/blob/8dd03310d0d1a924645437868542b3c279405338/src/components/Marquee.scss#L50

`min-width: 100%`

![image](https://user-images.githubusercontent.com/28438021/162566463-126c051c-1e1b-4849-ac9e-ea9b9f81b2e3.png)

`min-width: none`

![image](https://user-images.githubusercontent.com/28438021/162566472-fde99715-c129-4082-ad94-4655910104a2.png)

doing this in chrome dev tools fixes it for me but i haven't tried patching the package

**Comment by gustiyoga** [comment] 2022-04-26 13:23
Hi @maximousblk, setting min-width to max-content is works
But when I only have 1 item, let's say it has 1126px width and my screen is 1450px, and the marquee direction is left
It shows the first 2 items without a gap
![image](https://user-images.githubusercontent.com/7714897/165305994-7b2e8e4c-25f7-489b-a525-5f08684c0ad6.png)
(sorry, need to censor the image with black background)

After a while, the space was shown again. The third item will pop on the blank space when the second item reaches the left of the screen
![image](https://user-images.githubusercontent.com/7714897/165308262-6e26b0e2-4c08-4e3f-b214-efc614990b51.png)

**Comment by mickbut-ler** [comment] 2022-06-16 13:40
Are there any updates/fix for this issue?

**Comment by joshuaellis** [comment] 2022-06-29 12:42
> I've been experimenting with ways to fix this and i think i have found the problem.
> 
> setting the `min-width: 100%` to `min-width: max-content` or anything that has a similar effect solves this problem
> 
> https://github.com/justin-chu/react-fast-marquee/blob/8dd03310d0d1a924645437868542b3c279405338/src/components/Marquee.scss#L50
> 
> `min-width: 100%`
> 
> ![image](https://user-images.githubusercontent.com/28438021/162566463-126c051c-1e1b-4849-ac9e-ea9b9f81b2e3.png)
> 
> `min-width: none`
> 
> ![image](https://user-images.githubusercontent.com/28438021/162566472-fde99715-c129-4082-ad94-4655910104a2.png)
> 
> doing this in chrome dev tools fixes it for me but i haven't tried patching the package

This solution while somewhat effective doesn't resolve the root of the issue which is the library only clones the items once so if you render 3 items, the component will render 6 instead. Even with `min-width: max-content` set, if the 6 items do not fill the screen (e.g. on a 4K monitor) then it won't work and you'll have to manually duplicate your items as suggested above.

The long term solution I suppose would be to measure the width of the `.marquee` container, measure the width of the space the marquee exists in and use that as basis to understand how many times you must clone the items passed to the component.

**Comment by TomSmedley** [comment] 2022-09-21 14:29
At the moment, I just duplicated the children, it's not perfect but it works for now.

**Comment by justin-chu** [comment] 2023-04-23 07:00
Fixed in 1.4.0

**Closed by justin-chu** 2023-04-23 07:00 UTC
Labels: bug

**Comment by Luna-omni** [comment] 2023-05-22 02:49
![marqueegap](https://github.com/justin-chu/react-fast-marquee/assets/125844802/d5ed010d-7a78-448a-aed9-463e313f46b1)
Hello, I've encountered the same phenomenon.
When i removed div.marquee min-width:100% property in chrome developer tab it works well.
I read above issues and found this problem fixed in 1.4.0 so i updated latest version but i think it still has a problem and i don't know why.
Could you help me please?

**Comment by justin-chu** [comment] 2023-05-22 05:51
@Luna-omni could you please set `autoFill={true}` and see if this fixes it?

**Comment by Luna-omni** [comment] 2023-05-22 06:07
@justin-chu 
oh, it works perfectly so much thanks!! 😀

**Comment by BmAlkes** [comment] 2024-02-26 12:19
im try to use the marque fast and dont show all the pictures also the autofill dont work.. maybe some one know where is the problem?
![Screenshot_28](https://github.com/justin-chu/react-fast-marquee/assets/41919686/c574169b-6332-4698-9952-24ad1a5a580d)

`  <div className="w-full  bg-[#6FCFED]  mt-14   flex">
          <Marquee autoFill={true}>
            <img
              src={react}
              alt="react logo"
              className="  h-[115px] object-cover"
            />

            <div className="m-1  flex p-4 ">
              <img
                src={css}
                alt="css logo"
                className="  h-[115px] object-cover"
              />
            </div>

            <div className="m-1  flex p-4 ">
              <img
                src={nextjs}
                alt="nextjs logo"
                className=" h-[115px] object-cover"
              />
            </div>
            <div className="m-1  flex p-4 ">
              <img
                src={elementor}
                alt="elementor logo"
                className="  h-[115px] object-cover"
              />
            </div>
            <div className="m-1  flex p-4 ">
              <img
                src={firebase}
                alt="firebase logo"
                className="  h-[115px] object-cover"
              />
            </div>
            <div className="m-1 flex p-4 ">
              <img
                src={zustand}
                alt="zustand logo"
                className=" h-[115px] object-cover"
              />
            </div>
            <div className="m-1  flex p-4 ">
              <img
                src={redux}
                alt="redux logo"
                className=" h-[115px] object-cover"
              />
            </div>

            <div className="m-1  flex p-4 ">
              <img
                src={node}
                alt="node logo"
                className=" h-[115px] object-cover"
              />
            </div>
          </Marquee>`

**Comment by adelghaenian** [comment] 2024-08-02 09:44
I have the same issue but when I use autofill it makes it so laggy, and my chrome stutters alot. 
Here's my component code: 
`          <Marquee
            pauseOnHover
            className="h-full"
            speed={70}
            autoFill
          >
            {techStacks.map((ts) => (
              <TechStackItem ts={ts} key={ts}></TechStackItem>
            ))}
          </Marquee>`

`import React from "react";

interface iTechStackItem {
  ts: string;
}
const TechStackItem: React.FC<iTechStackItem> = (props) => {
  return (
    <div className="flex flex-col items-center gap-2 mr-12">
      <img
        height="48"
        width="48"
        className=""
        src={`https://cdn.simpleicons.org/${props.ts}`}
      />
      <p className="text-xl text-center capitalize text-text-subtitle">
        {props.ts
          .replace("dot", ".")
          .replace("adobe", "A. ")
          .replace("amazonwebservices", "AWS")}
      </p>
    </div>
  );
};

export default TechStackItem;
`

**Comment by YousafKhan1** [comment] 2025-02-03 19:58
2025 still the problem exist I had two application in one it worked in second it had space but in second I just remove margin.
inside marqee tag wrap images through div element then add padding instead of margin

**Comment by Hahlh** [comment] 2025-02-04 04:11
@YousafKhan1 

One viable workaround is to simply duplicate your elements to reach a sufficient number:

Along the lines of:

```javascript

const finalLogoArray = [...logoArray, ...logoArray, ...logoArray]

<Marquee className="flex justify-between w-full h-20 lg:max-w-10/12">
        <div className="flex justify-between">
          {finalLogoArray.map(logo => { [your return JSX]}
        </div>
</Marquee>
```

Hope that helps!
