### ISSUE TITLE
no gradient width in React 16-17

### ISSUE THREAD

**Issue by FriendlyNGeeks** [justin-chu/react-fast-marquee#26] opened 2021-09-09 05:49 UTC
Keeps adding "function(){[native code]}" to the end of the css var

`
    --gradient-color: rgba(255, 255, 255, 1), rgba(255, 255, 255, 0);
    --gradient-width: 100px,function () { [native code] };
`
`
<ReactFastMarquee speed={speed} gradient={gradientBool} gradientColor={gradColor} gradientWidth={gradientWidth}>
`

**Comment by justin-chu** [comment] 2023-04-22 19:35
Unable to reproduce this issue, closing for now.

**Closed by justin-chu** 2023-04-22 19:35 UTC
