### ISSUE TITLE
When reload the page react-fast-marquee is accelarating

### ISSUE THREAD

**Issue by efemevlut** [justin-chu/react-fast-marquee#9] opened 2021-06-11 07:20 UTC
I am using png file and When reload the page react-fast-marquee is accelarating.
My code snippet
`<Marquee speed={100}>
      <div className={"marquee-style"}>
        <img src="/example1.png" width="50%"/>
      </div>
      <div className={"marquee-style"}>
        <img src="/example2.png"  width="50%"/>
      </div>
      <div className={"marquee-style"}>
        <img src="/example3.png"  width="50%"/>
      </div>
      </Marquee>`

**Comment by justin-chu** [comment] 2021-06-12 19:31
I'll look into this.

**Comment by justin-chu** [comment] 2021-06-20 19:33
Unfortunately, I'm unable to reproduce this issue. Do you have more details? It could be an issue with the `marquee-style` class, but I'm not sure.

**Comment by gustavoferrara** [comment] 2022-05-23 06:25
Any updates on this? Experiencing the same issue.

**Comment by codyarose** [comment] 2022-06-06 21:35
Same issue here. 
Also using Suspense, and I noticed that the issues resolves itself if the viewport size is changed.

The speed is controlled by a css variable on `.marquee` called `--duration`. My temporary fix is to manually override that variable `--duration: 60s !important`

**Comment by kylewetton** [comment] 2022-12-10 21:40
Until this is fixed, the lib isn't worth using unfortunately.

**Comment by justin-chu** [comment] 2023-04-23 07:01
Fixed in 1.4.0

**Closed by justin-chu** 2023-04-23 07:01 UTC
Labels: bug
